spring:
  application:
    name: centralized-config-service
  profiles:
    active: local,development,production
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mohannara/spring-config
server:
  port: 8888
management:
  security:
    enabled: false